#@data/values-schema

---

#@schema/desc "Settings for the cert-manager-webhook-hetzner."
webhook:
  #@schema/desc "The number of replicas. In order to enable high availability, at least 3 replicas are recommended."
  #@schema/validation min=1
  replicas: 1
